export const requiredProductFelids = [
    'title',
    'price',
    'media',
    'category',
]

export const colorsArray = [
    { value: 'aliceblue', label: 'aliceblue', color: '#F0F8FF' },
    { value: 'antiquewhite', label: 'antiquewhite', color: '#FAEBD7' },
    { value: 'aqua', label: 'aqua', color: '#00FFFF' },
    { value: 'aquamarine', label: 'aquamarine', color: '#7FFFD4' },
    { value: 'azure', label: 'azure', color: '#F0FFFF' },
    { value: 'beige', label: 'beige', color: '#F5F5DC' },
    { value: 'bisque', label: 'bisque', color: '#FFE4C4' },
    { value: 'black', label: 'black', color: '#000000' },
    { value: 'blanchedalmond', label: 'blanchedalmond', color: '#FFEBCD' },
    { value: 'blue', label: 'blue', color: '#0000FF' },
    { value: 'blueviolet', label: 'blueviolet', color: '#8A2BE2' },
    { value: 'brown', label: 'brown', color: '#A52A2A' },
    { value: 'burlywood', label: 'burlywood', color: '#DEB887' },
    { value: 'cadetblue', label: 'cadetblue', color: '#5F9EA0' },
    { value: 'chartreuse', label: 'chartreuse', color: '#7FFF00' },
    { value: 'chocolate', label: 'chocolate', color: '#D2691E' },
    { value: 'coral', label: 'coral', color: '#FF7F50' },
    { value: 'cornflowerblue', label: 'cornflowerblue', color: '#6495ED' },
    { value: 'cornsilk', label: 'cornsilk', color: '#FFF8DC' },
    { value: 'crimson', label: 'crimson', color: '#DC143C' },
    { value: 'cyan', label: 'cyan', color: '#00FFFF' },
    { value: 'darkblue', label: 'darkblue', color: '#00008B' },
    { value: 'darkcyan', label: 'darkcyan', color: '#008B8B' },
    { value: 'darkgoldenrod', label: 'darkgoldenrod', color: '#B8860B' },
    { value: 'darkgray', label: 'darkgray', color: '#A9A9A9' },
    { value: 'darkgrey', label: 'darkgrey', color: '#A9A9A9' },
    { value: 'darkgreen', label: 'darkgreen', color: '#006400' },
    { value: 'darkkhaki', label: 'darkkhaki', color: '#BDB76B' },
    { value: 'darkmagenta', label: 'darkmagenta', color: '#8B008B' },
    { value: 'darkolivegreen', label: 'darkolivegreen', color: '#556B2F' },
    { value: 'darkorange', label: 'darkorange', color: '#FF8C00' },
    { value: 'darkorchid', label: 'darkorchid', color: '#9932CC' },
    { value: 'darkred', label: 'darkred', color: '#8B0000' },
    { value: 'darksalmon', label: 'darksalmon', color: '#E9967A' },
    { value: 'darkseagreen', label: 'darkseagreen', color: '#8FBC8F' },
    { value: 'darkslateblue', label: 'darkslateblue', color: '#483D8B' },
    { value: 'darkslategray', label: 'darkslategray', color: '#2F4F4F' },
    { value: 'darkslategrey', label: 'darkslategrey', color: '#2F4F4F' },
    { value: 'darkturquoise', label: 'darkturquoise', color: '#00CED1' },
    { value: 'darkviolet', label: 'darkviolet', color: '#9400D3' },
    { value: 'deeppink', label: 'deeppink', color: '#FF1493' },
    { value: 'deepskyblue', label: 'deepskyblue', color: '#00BFFF' },
    { value: 'dimgray', label: 'dimgray', color: '#696969' },
    { value: 'dimgrey', label: 'dimgrey', color: '#696969' },
    { value: 'dodgerblue', label: 'dodgerblue', color: '#1E90FF' },
    { value: 'firebrick', label: 'firebrick', color: '#B22222' },
    { value: 'floralwhite', label: 'floralwhite', color: '#FFFAF0' },
    { value: 'forestgreen', label: 'forestgreen', color: '#228B22' },
    { value: 'fuchsia', label: 'fuchsia', color: '#FF00FF' },
    { value: 'gainsboro', label: 'gainsboro', color: '#DCDCDC' },
    { value: 'ghostwhite', label: 'ghostwhite', color: '#F8F8FF' },
    { value: 'gold', label: 'gold', color: '#FFD700' },
    { value: 'goldenrod', label: 'goldenrod', color: '#DAA520' },
    { value: 'gray', label: 'gray', color: '#808080' },
    { value: 'grey', label: 'grey', color: '#808080' },
    { value: 'green', label: 'green', color: '#008000' },
    { value: 'greenyellow', label: 'greenyellow', color: '#ADFF2F' },
    { value: 'honeydew', label: 'honeydew', color: '#F0FFF0' },
    { value: 'hotpink', label: 'hotpink', color: '#FF69B4' },
    { value: 'indianred', label: 'indianred', color: '#CD5C5C' },
    { value: 'indigo', label: 'indigo', color: '#4B0082' },
    { value: 'ivory', label: 'ivory', color: '#FFFFF0' },
    { value: 'khaki', label: 'khaki', color: '#F0E68C' },
    { value: 'lavender', label: 'lavender', color: '#E6E6FA' },
    { value: 'lavenderblush', label: 'lavenderblush', color: '#FFF0F5' },
    { value: 'lawngreen', label: 'lawngreen', color: '#7CFC00' },
    { value: 'lemonchiffon', label: 'lemonchiffon', color: '#FFFACD' },
    { value: 'lightblue', label: 'lightblue', color: '#ADD8E6' },
    { value: 'lightcoral', label: 'lightcoral', color: '#F08080' },
    { value: 'lightcyan', label: 'lightcyan', color: '#E0FFFF' },
    { value: 'lightgoldenrodyellow', label: 'lightgoldenrodyellow', color: '#FAFAD2' },
    { value: 'lightgray', label: 'lightgray', color: '#D3D3D3' },
    { value: 'lightgrey', label: 'lightgrey', color: '#D3D3D3' },
    { value: 'lightgreen', label: 'lightgreen', color: '#90EE90' },
    { value: 'lightpink', label: 'lightpink', color: '#FFB6C1' },
    { value: 'lightsalmon', label: 'lightsalmon', color: '#FFA07A' },
    { value: 'lightseagreen', label: 'lightseagreen', color: '#20B2AA' },
    { value: 'lightskyblue', label: 'lightskyblue', color: '#87CEFA' },
    { value: 'lightslategray', label: 'lightslategray', color: '#778899' },
    { value: 'lightslategrey', label: 'lightslategrey', color: '#778899' },
    { value: 'lightsteelblue', label: 'lightsteelblue', color: '#B0C4DE' },
    { value: 'lightyellow', label: 'lightyellow', color: '#FFFFE0' },
    { value: 'lime', label: 'lime', color: '#00FF00' },
    { value: 'limegreen', label: 'limegreen', color: '#32CD32' },
    { value: 'linen', label: 'linen', color: '#FAF0E6' },
    { value: 'magenta', label: 'magenta', color: '#FF00FF' },
    { value: 'maroon', label: 'maroon', color: '#800000' },
    { value: 'mediumaquamarine', label: 'mediumaquamarine', color: '#66CDAA' },
    { value: 'mediumblue', label: 'mediumblue', color: '#0000CD' },
    { value: 'mediumorchid', label: 'mediumorchid', color: '#BA55D3' },
    { value: 'mediumpurple', label: 'mediumpurple', color: '#9370DB' },
    { value: 'mediumseagreen', label: 'mediumseagreen', color: '#3CB371' },
    { value: 'mediumslateblue', label: 'mediumslateblue', color: '#7B68EE' },
    { value: 'mediumspringgreen', label: 'mediumspringgreen', color: '#00FA9A' },
    { value: 'mediumturquoise', label: 'mediumturquoise', color: '#48D1CC' },
    { value: 'mediumvioletred', label: 'mediumvioletred', color: '#C71585' },
    { value: 'midnightblue', label: 'midnightblue', color: '#191970' },
    { value: 'mintcream', label: 'mintcream', color: '#F5FFFA' },
    { value: 'mistyrose', label: 'mistyrose', color: '#FFE4E1' },
    { value: 'moccasin', label: 'moccasin', color: '#FFE4B5' },
    { value: 'navajowhite', label: 'navajowhite', color: '#FFDEAD' },
    { value: 'navy', label: 'navy', color: '#000080' },
    { value: 'oldlace', label: 'oldlace', color: '#FDF5E6' },
    { value: 'olive', label: 'olive', color: '#808000' },
    { value: 'olivedrab', label: 'olivedrab', color: '#6B8E23' },
    { value: 'orange', label: 'orange', color: '#FFA500' },
    { value: 'orangered', label: 'orangered', color: '#FF4500' },
    { value: 'orchid', label: 'orchid', color: '#DA70D6' },
    { value: 'palegoldenrod', label: 'palegoldenrod', color: '#EEE8AA' },
    { value: 'palegreen', label: 'palegreen', color: '#98FB98' },
    { value: 'paleturquoise', label: 'paleturquoise', color: '#AFEEEE' },
    { value: 'palevioletred', label: 'palevioletred', color: '#DB7093' },
    { value: 'papayawhip', label: 'papayawhip', color: '#FFEFD5' },
    { value: 'peachpuff', label: 'peachpuff', color: '#FFDAB9' },
    { value: 'peru', label: 'peru', color: '#CD853F' },
    { value: 'pink', label: 'pink', color: '#FFC0CB' },
    { value: 'plum', label: 'plum', color: '#DDA0DD' },
    { value: 'powderblue', label: 'powderblue', color: '#B0E0E6' },
    { value: 'purple', label: 'purple', color: '#800080' },
    { value: 'rebeccapurple', label: 'rebeccapurple', color: '#663399' },
    { value: 'red', label: 'red', color: '#FF0000' },
    { value: 'rosybrown', label: 'rosybrown', color: '#BC8F8F' },
    { value: 'royalblue', label: 'royalblue', color: '#4169E1' },
    { value: 'saddlebrown', label: 'saddlebrown', color: '#8B4513' },
    { value: 'salmon', label: 'salmon', color: '#FA8072' },
    { value: 'sandybrown', label: 'sandybrown', color: '#F4A460' },
    { value: 'seagreen', label: 'seagreen', color: '#2E8B57' },
    { value: 'seashell', label: 'seashell', color: '#FFF5EE' },
    { value: 'sienna', label: 'sienna', color: '#A0522D' },
    { value: 'silver', label: 'silver', color: '#C0C0C0' },
    { value: 'skyblue', label: 'skyblue', color: '#87CEEB' },
    { value: 'slateblue', label: 'slateblue', color: '#6A5ACD' },
    { value: 'slategray', label: 'slategray', color: '#708090' },
    { value: 'slategrey', label: 'slategrey', color: '#708090' },
    { value: 'snow', label: 'snow', color: '#FFFAFA' },
    { value: 'springgreen', label: 'springgreen', color: '#00FF7F' },
    { value: 'steelblue', label: 'steelblue', color: '#4682B4' },
    { value: 'tan', label: 'tan', color: '#D2B48C' },
    { value: 'teal', label: 'teal', color: '#008080' },
    { value: 'thistle', label: 'thistle', color: '#D8BFD8' },
    { value: 'tomato', label: 'tomato', color: '#FF6347' },
    { value: 'turquoise', label: 'turquoise', color: '#40E0D0' },
    { value: 'violet', label: 'violet', color: '#EE82EE' },
    { value: 'wheat', label: 'wheat', color: '#F5DEB3' },
    { value: 'white', label: 'white', color: '#FFFFFF' },
    { value: 'whitesmoke', label: 'whitesmoke', color: '#F5F5F5' },
    { value: 'yellow', label: 'yellow', color: '#FFFF00' },
    { value: 'yellowgreen', label: 'yellowgreen', color: '#9ACD32' }
  ];

export const additionalAttributes = [
    'Size',
    'Variant',
    'Material',
    'Height',
    'Width',
]


export const deliveryTime = [
    { label: "1-2 Days", value: "1-2" },
    { label: "3-4 Days", value: "3-4" },
    { label: "5-6 Days", value: "5-6" },
    { label: "7-8 Days", value: "7-8" },
    { label: "9-10 Days", value: "9-10" },
    { label: "11-12 Days", value: "11-12" },
    { label: "13-14 Days", value: "13-14" },
    { label: "15-16 Days", value: "15-16" },
    { label: "17-18 Days", value: "17-18" },
    { label: "19-20 Days", value: "19-20" },
    { label: "21-22 Days", value: "21-22" },
    { label: "23-24 Days", value: "23-24" },
    { label: "25-26 Days", value: "25-26" },
    { label: "27-28 Days", value: "27-28" },
    { label: "29-30 Days", value: "29-30" },
    { label: "31-32 Days", value: "31-32" },
    { label: "33-34 Days", value: "33-34" },
    { label: "35-36 Days", value: "35-36" },
    { label: "37-38 Days", value: "37-38" },
    { label: "39-40 Days", value: "39-40" },
    { label: "41-42 Days", value: "41-42" },
    { label: "43-44 Days", value: "43-44" },
    { label: "45-46 Days", value: "45-46" },
    { label: "47-48 Days", value: "47-48" },
    { label: "49-50 Days", value: "49-50" },
    { label: "51-52 Days", value: "51-52" },
    { label: "53-54 Days", value: "53-54" },
]